### ISSUE TITLE
[BUG] Cards not displaying

### ISSUE THREAD

**Issue by SpeckyYT** [dimdenGD/blackjack-js#1]
I was trying to implement this system into a Discord Bot, but then I noticed that when hitting, the sequence of the player cards changed and the new one doesn't display.

![image](https://user-images.githubusercontent.com/40666126/103179976-aa53ab80-4891-11eb-9ff7-34b7306d6fc2.png)
^ 4 + 10 = 14    |   10 + 4 = 24 ?

![image](https://media.discordapp.net/attachments/514911291350056990/792872520125644840/unknown.png)
here it happened too.

Sometimes it works and sometimes it doesn't.

If you ask about the code, I use the one from the README
```js
game.player.cards.map(i => i.image).join(", ")
```

**Comment by dimdenGD** [comment]
Hi, should be fixed now
